### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by Sanjeevsetu** [ahmedkaludi/push-notification#62]
- [x]  Show message Upgrade to premimum api key in plugin dashboard for free users
- [x] put some gap here ( https://prnt.sc/E7w6EgbIBssM )
- [x] When we click on buy plan it takes to register page where there is no option to login if user is already register.
- [x] Do not show Get Started Page for logged in users ( https://prnt.sc/B8HZW6VjQrE1 ). Take user to dashboard 
- [x] Put validation on notification form ( https://prnt.sc/RyzcQhfWmL2Z )
- [x] If user is using pro api than we should show pro information in plugin section as well
- [x] Update readme and add pro features
- [x] If API key is not activated than do not show other tabs as it shows empty content.
